# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='check',
            field=models.CharField(default='out', max_length=200),
            preserve_default=False,
        ),
    ]
